name: Build resume with LaTex
on:
  push:
    branches:
      - main
jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: xi-qiu-resume.tex
      - name: Move resume to gh-pages branch
        run: |
          git --version
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git fetch
          git status
          git add xi-qiu-resume.pdf
          git stash -- xi-qiu-resume.pdf
          git checkout gh-pages
          git checkout stash -- xi-qiu-resume.pdf
          git status
      - name: Add & Commit to gh-pages
        uses: EndBug/add-and-commit@v9.0.1
        with:
          default_author: github_actions
          add: 'xi-qiu-resume.pdf'
          new_branch: gh-pages
