name: Build resume with LaTex
on: [push]
jobs:
  build_resume:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: xi-qiu-resume.tex
      - name: Add & Commit to gh-pages
        uses: EndBug/add-and-commit@v9.0.1
        with:
          default_author: github_actions
          add: 'xi-qiu-resume.pdf'
          new_branch: gh-pages
